import express from 'express';
import romanize from '../api/romanize.js';
import music from '../api/music-romanize.js';
import library from '../api/song-library.js';
import auth from '../api/app-auth.js';
import liveLyrics from '../api/live-lyrics.js';
const app=express();app.use(express.json({limit:'32kb'}));
for(const [path,handler] of [['romanize',romanize],['music-romanize',music],['song-library',library],['app-auth',auth],['live-lyrics',liveLyrics]])app.all(`/api/${path}`,handler);
app.get('/health',(_,res)=>res.json({status:'ok'}));
app.listen(process.env.PORT||3000);
